@startuml
class LabOne.Account.Account {
- int _id
- double _balance
- {static} double annualInterestRate
+ int getId()
+ void setId(int)
+ double getBalance()
+ void setBalance(double)
+ {static} double getAnnualInterestRate()
+ {static} void setAnnualInterestRate(double)
+ double getMonthlyInterest()
+ void withdraw(double)
+ void deposit(double)
}
class LabOne.Account.AccountException {
- AccountExceptionType exceptionType
+ AccountExceptionType getExceptionType()
}
enum LabOne.Account.AccountExceptionType

LabOne.Account.Account .> LabOne.Account.AccountException
LabOne.Account.AccountException -> LabOne.Account.AccountExceptionType
Exception <|-u- LabOne.Account.AccountException
@enduml